version: '3.8'

services:
  postgres:
    container_name: ms-user
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
      
      - POSTGRES_DB=ms-user